"""Public, factual product content used by Creana's GEO pages."""

PUBLIC_PAGE_ORDER = (
    "introduction", "community", "features", "ai_features", "pricing",
    "supported_platforms", "how_it_works", "faq", "about", "contact",
    "privacy", "terms", "ai_policy",
)

PUBLIC_PAGES = {
    "introduction": {
        "route_name": "introduction", "title": "What Is Creana? | Introduction",
        "description": "Learn what Creana is, who it is for, and how its content creation, campaign planning, scheduling, community, and AI tools work.",
        "eyebrow": "Introduction", "heading": "What is Creana?",
        "lead": "Creana is an AI-powered social media content workspace for creators, influencers, students, and small businesses.",
        "differentiators": ["Writing assistance for captions, hashtags, and ideas", "One workspace for drafts, posts, and campaigns", "A public creator community", "Insights grounded in activity recorded inside Creana"],
        "sections": [
            {"heading": "Who Creana is for", "paragraphs": ["Creana is for people who want a clearer way to prepare, organise, share, and learn from social media content, including individual creators, influencers, students, and small businesses."]},
            {"heading": "The problem Creana solves", "paragraphs": ["Content ideas, drafts, campaigns, publishing decisions, and performance notes often live in separate places. Creana brings those parts of the content process into one approachable workspace."]},
            {"heading": "A clearer content workspace", "paragraphs": ["Creana connects creation, organisation, community participation, and in-platform learning without presenting itself as an external social-account analytics service."]},
        ], "related": ("features", "ai_features", "supported_platforms"),
        "inline_links": (("features", "Explore all features"), ("ai_features", "Compare AI tools"), ("supported_platforms", "Review platform support"), ("how_it_works", "See the workflow")),
    },
    "community": {
        "route_name": "community", "title": "Creana Community and Community Guidelines",
        "description": "Learn how Creana's public creator community works and review the rules for safe, respectful sharing.",
        "eyebrow": "Community", "heading": "Participating in the Creana community",
        "lead": "Creana provides a public creator space for discovering content, maintaining profiles, and interacting respectfully.",
        "sections": [
            {"heading": "Ways to participate", "bullets": ["Browse public posts and profiles", "Comment on, like, and share public content", "Follow creators", "Discover posts by keyword or hashtag"]},
            {"heading": "Choose what you share", "paragraphs": ["Users choose whether eligible content is public or private. Public content may be visible in the feed, on profiles, and to search engines; private content is not intended for public discovery."]},
            {"heading": "Participate respectfully", "paragraphs": ["Respect other people, use content you have the right to share, and do not harass, impersonate, spam, deceive, or publish harmful or illegal material. Detailed service obligations appear in the Terms, and AI-specific responsibilities appear in the AI Policy."]},
            {"heading": "Moderation outcomes", "paragraphs": ["Creana may remove content, limit visibility, restrict features, or suspend accounts when conduct violates community or service rules or creates a safety or security risk."]},
        ], "related": ("terms", "privacy", "ai_policy"),
    },
    "features": {
        "route_name": "features", "title": "Creana Features | Content, Campaigns and Analytics",
        "description": "Explore how Creana supports content creation, campaign planning, scheduling, community participation, and in-platform analytics.",
        "eyebrow": "Features", "heading": "What can Creana do?",
        "lead": "Creana brings creation, organisation, publishing inside Creana, community participation, and performance review into one content workspace.",
        "feature_groups": [
            {
                "heading": "Content Creation",
                "intro": "Choose a format, prepare the content, and decide when and where it should be visible inside Creana.",
                "features": [
                    {"name": "Article", "purpose": "Write longer, structured content.", "scenario": "Use it for guides, explanations, updates, or ideas that need more context than a short caption.", "description": "The article workflow provides a rich text body, a separate short caption, tags, and an optional cover image."},
                    {"name": "Image", "purpose": "Pair a visual with a concise message.", "scenario": "Use it for a single design, photograph, announcement, or visual update.", "description": "Upload an image, add a caption and hashtags, then save, schedule, or publish it inside Creana."},
                    {"name": "Video", "purpose": "Share video content and review in-platform viewing activity.", "scenario": "Use it when motion, demonstration, or presentation is central to the post.", "description": "Upload a supported video, add its supporting copy, and publish it with a thumbnail where available."},
                    {"name": "Carousel", "purpose": "Present several images as one post.", "scenario": "Use it for step-by-step visuals, collections, comparisons, or a sequence of related ideas.", "description": "Arrange multiple images in a single post while keeping one caption, visibility setting, and publishing status."},
                    {"name": "Public / Private", "purpose": "Control who can discover a post.", "scenario": "Use Public for eligible community content and Private for content that should remain within the owner's authorised workspace view.", "description": "Only eligible published public posts are intended for anonymous discovery and search indexing."},
                    {"name": "Draft", "purpose": "Keep unfinished work without publishing it.", "scenario": "Use a draft while researching, editing, awaiting approval, or preparing media.", "description": "Drafts remain editable and are not included in Creana's public feed or public sitemap."},
                    {"name": "Rich editor", "purpose": "Structure article content for easier reading.", "scenario": "Use it when an article needs paragraphs, headings, lists, emphasis, or text alignment.", "description": "The editor supports a controlled set of formatting options that are sanitised when the article is displayed."},
                ],
            },
            {
                "heading": "Campaign Planning",
                "intro": "Group related work so individual posts contribute to a clear campaign plan.",
                "features": [
                    {"name": "Campaign", "purpose": "Keep related posts together.", "scenario": "Use a campaign for a launch, event, promotion, awareness theme, or multi-post content series.", "description": "A campaign provides one place to review the posts connected to the same body of work."},
                    {"name": "Objectives", "purpose": "Record what the campaign is intended to achieve.", "scenario": "Use an objective to keep planning decisions aligned with the campaign's intended outcome.", "description": "Campaign context helps users organise work and interpret the in-platform results shown by Creana."},
                    {"name": "Scheduling", "purpose": "Coordinate when campaign posts become available inside Creana.", "scenario": "Use it when several posts need a planned sequence rather than being released at once.", "description": "Scheduled campaign posts retain their campaign relationship while waiting for their chosen release time."},
                    {"name": "Organisation", "purpose": "Reduce scattered content and status tracking.", "scenario": "Use campaign organisation when drafts, scheduled posts, and published work belong to one initiative.", "description": "Campaign views keep the relevant content, status, platform labels, and analytics context together."},
                ],
            },
            {
                "heading": "Scheduling",
                "intro": "Prepare content in advance and choose a future release time inside Creana.",
                "features": [
                    {"name": "Schedule a post", "purpose": "Set a future publishing date and time.", "scenario": "Use it after the content is ready but should not appear in the Creana feed immediately.", "description": "Choose the scheduled status and a valid future date and time when creating or editing the post."},
                    {"name": "Manage Scheduled Posts", "purpose": "Review or change upcoming content.", "scenario": "Use it when timing, copy, media, campaign assignment, or visibility needs to change before release.", "description": "Scheduled posts remain editable and can be rescheduled before the publishing process makes them available."},
                    {"name": "Why use scheduling", "purpose": "Separate content preparation from release time.", "scenario": "Use it to prepare a consistent sequence, coordinate a campaign, or avoid last-minute publishing work.", "description": "Creana scheduling controls release inside Creana; it does not claim automatic publishing to external social platforms."},
                ],
            },
            {
                "heading": "Community",
                "intro": "Discover eligible public work and participate in the Creana creator community.",
                "features": [
                    {"name": "Feed", "purpose": "Browse published public posts.", "scenario": "Use it to discover recent creator content and filter the currently loaded feed by keyword or hashtag.", "description": "The feed presents eligible public posts with their author, format, content preview, and engagement controls."},
                    {"name": "Follow", "purpose": "Maintain a connection to another creator profile.", "scenario": "Use it when you want the relationship to appear in profile follower and following information.", "description": "Following is an in-platform community action and does not create an external social-platform connection."},
                    {"name": "Like", "purpose": "Show appreciation for a public post.", "scenario": "Use it as a lightweight response when a post is useful, relevant, or enjoyable.", "description": "Likes contribute to the engagement information recorded for that post inside Creana."},
                    {"name": "Comment", "purpose": "Discuss a post with its author and community.", "scenario": "Use it to ask a question, add context, or provide a relevant response.", "description": "Comments and replies appear with the public post and must follow Creana's community rules."},
                    {"name": "Share", "purpose": "Feature another eligible public post on a profile's shared-post view.", "scenario": "Use it when a post is worth passing on to people who view your Creana profile.", "description": "Sharing records an in-platform share; it does not automatically repost content to an external network."},
                ],
            },
            {
                "heading": "Analytics",
                "intro": "Review activity generated or tracked inside Creana without presenting it as imported external-platform analytics.",
                "features": [
                    {"name": "Dashboard", "purpose": "See a workspace-level performance overview.", "scenario": "Use it when reviewing recent content activity and deciding where to investigate further.", "description": "The dashboard summarises relevant Creana posts, engagement, and trends available to the current workspace."},
                    {"name": "Post Analytics", "purpose": "Inspect the performance of one post.", "scenario": "Use it after publishing when you need a focused view of that post's views and engagement.", "description": "Post analytics use the activity Creana records for the selected post."},
                    {"name": "Campaign Analytics", "purpose": "Review results across related campaign posts.", "scenario": "Use it to compare the content contributing to one campaign objective.", "description": "Campaign analytics aggregate relevant in-platform activity for posts associated with the campaign."},
                    {"name": "Video Retention", "purpose": "Understand how viewing changes across a video.", "scenario": "Use it when a published Creana video has enough watch-session or timed-engagement data to interpret.", "description": "Retention views are based on video activity recorded inside Creana and may be limited when the sample is small."},
                ],
            },
            {
                "heading": "AI",
                "intro": "This feature is explained in the AI Features page.",
                "features": [],
                "link": ("ai_features", "Learn more about AI Features"),
            },
        ],
        "sections": [], "related": ("ai_features", "community", "supported_platforms"), "software_schema": True,
    },
    "ai_features": {
        "route_name": "ai_features", "title": "Creana AI Features | Captions, Feedback and Insights",
        "description": "Understand Creana's AI caption generator, hashtag suggestions, content feedback, and insights based on data collected within Creana.",
        "eyebrow": "AI features", "heading": "Which Creana AI tool should you use?",
        "lead": "Use this reference to understand what each Creana AI feature does, when it is useful, and where human review is still required.",
        "tool_groups": [
            {"label": "AI writing tools", "heading": "Create and refine content", "items": ["AI Caption Generator", "Hashtag suggestions", "Article-style content support", "AI content feedback"], "summary": "These tools do not require analytics data. Users can review and copy the writing for content intended for external platforms."},
            {"label": "Creana-data tools", "heading": "Understand in-platform activity", "items": ["Post performance insights", "Campaign insights", "Dashboard insights", "Video-retention feedback"], "summary": "These tools require relevant posts, campaigns, engagement, watch sessions, or retention activity recorded inside Creana."},
        ],
        "matrix": [
            ("Write a caption", "AI Caption Generator", "No"), ("Generate hashtags", "Hashtag suggestions", "No"), ("Improve post wording", "AI content feedback", "No"), ("Review post performance", "Post performance insights", "Yes"), ("Review campaign performance", "Campaign insights", "Yes"), ("Review workspace trends", "Dashboard insights", "Yes"), ("Understand video retention", "Video-retention feedback", "Yes"),
        ],
        "ai_feature_docs": [
            {"name": "AI Caption Generator", "what_it_does": "Produces a draft caption from the topic, platform, tone, and content details supplied by the user.", "when_to_use": "Use it when starting a caption, exploring a different angle, or turning a content idea into an editable first draft.", "limitations": "The output can miss context, facts, rights, brand requirements, or platform-specific rules and should not be treated as final copy.", "workflow": ["Choose the post format and target platform.", "Provide a clear topic or content description.", "Generate a caption.", "Review facts, tone, length, and rights before saving or publishing."]},
            {"name": "Hashtag Suggestions", "what_it_does": "Suggests a bounded set of hashtags based on the content information and settings available to the request.", "when_to_use": "Use it when a post needs relevant topic labels or when an existing hashtag set needs another starting point.", "limitations": "Suggestions do not guarantee reach, trend relevance, platform eligibility, or improved performance.", "workflow": ["Describe the post accurately.", "Request hashtag suggestions.", "Remove irrelevant, misleading, or overly broad tags.", "Keep only tags that genuinely match the published content."]},
            {"name": "AI Content Feedback", "what_it_does": "Reviews selected title, caption, article, or hashtag content and returns an improvement suggestion.", "when_to_use": "Use it before publishing when wording, clarity, structure, or audience fit needs a second review.", "limitations": "Feedback is generated from the information available to Creana and cannot verify every factual, legal, cultural, or brand consideration.", "workflow": ["Select the content field to review.", "Provide the current text and relevant post context.", "Compare the suggestion with the original.", "Accept only changes that remain accurate and appropriate."]},
            {"name": "Dashboard Insights", "what_it_does": "Summarises patterns in the recent workspace activity and analytics available inside Creana.", "when_to_use": "Use it when reviewing overall performance and deciding which posts or campaigns deserve closer attention.", "limitations": "It depends on the quality and quantity of Creana-recorded data and does not import or infer complete external social-account performance.", "workflow": ["Allow enough relevant activity to be recorded.", "Open the dashboard insight.", "Review the supporting metrics and sample size.", "Use the result as one input to the next content decision."]},
            {"name": "Campaign Insights", "what_it_does": "Interprets the posts and in-platform performance information associated with a selected campaign.", "when_to_use": "Use it when comparing campaign content, reviewing progress, or planning the next post in the same initiative.", "limitations": "An insight may be weak when a campaign has few posts, little activity, or an unclear objective, and it does not represent external-platform analytics.", "workflow": ["Keep the campaign objective and post assignments current.", "Collect relevant in-platform activity.", "Generate the campaign insight.", "Check the evidence before changing the campaign plan."]},
            {"name": "Video Retention Feedback", "what_it_does": "Explains retention and timed-engagement patterns available for a video viewed inside Creana.", "when_to_use": "Use it after a video has enough watch sessions to investigate its opening, pacing, or drop-off points.", "limitations": "Small samples and incomplete watch data can make patterns unreliable; the feature does not measure viewers on external video platforms.", "workflow": ["Publish an eligible video inside Creana.", "Allow watch-session and timed-engagement data to accumulate.", "Review the retention chart and generated feedback together.", "Test one evidence-supported change in a future video."]},
        ],
        "sections": [{"heading": "Responsible AI", "paragraphs": ["AI output may be incomplete, inaccurate, or unsuitable. Users should review facts, rights, tone, and platform requirements before using any suggestion.", "Creana AI assists with drafting and interpreting available signals. The user remains responsible for the final content and decision.", "AI features do not automatically publish content. A user must review and complete the relevant save, schedule, or publish action."]}],
        "related": ("ai_policy", "pricing", "supported_platforms"), "software_schema": True,
    },
    "pricing": {
        "route_name": "pricing", "title": "Creana Pricing | AI Membership",
        "description": "See Creana's current USD $5 monthly membership concept and learn which AI functionality is member-only.",
        "eyebrow": "Pricing", "heading": "How does Creana membership work?",
        "lead": "The application currently displays member access at USD $5/month. Current in-product checkout information takes precedence.",
        "table": [
            ("Create public content", "✓", "✓"), ("Browse community posts", "✓", "✓"), ("AI caption and writing tools", "✕", "✓"), ("AI insights", "✕", "✓"), ("Campaign and post analytics", "✓", "✓"), ("Video-retention feedback", "✕", "✓"), ("Membership price", "$0", "USD $5/month"), ("Best for", "Exploring the community", "Using member AI tools"),
        ],
        "sections": [{"heading": "Current pricing information", "paragraphs": ["Pricing, limits, and feature availability may change as Creana develops. Review the current checkout details before subscribing."]}],
        "related": ("ai_features", "faq", "terms"), "software_schema": True,
    },
    "supported_platforms": {
        "route_name": "supported_platforms", "title": "Platforms Supported by Creana Content Tools",
        "description": "Learn how Creana helps prepare content for social platforms and how content targets differ from external publishing and analytics integrations.",
        "eyebrow": "Supported platforms", "heading": "Which platforms can Creana help with?",
        "lead": "Creana helps users prepare writing for external social channels while keeping content targets, publishing, and analytics integrations clearly distinguished.",
        "table": [
            ("TikTok", "Yes, by copy and paste", "Yes", "Not currently claimed"), ("Instagram", "Yes, by copy and paste", "Yes", "Not currently claimed"), ("YouTube", "Yes, by copy and paste", "Yes", "Not currently claimed"), ("Facebook", "Yes, by copy and paste", "Yes", "Not currently claimed"), ("X / Twitter", "Yes, by copy and paste", "Yes", "Not currently claimed"), ("Reddit", "Yes, by copy and paste", "Yes", "Not currently claimed"), ("LinkedIn", "Yes, by copy and paste", "Not currently listed", "Not currently claimed"), ("Other platforms", "Where the generated writing is suitable", "Not currently listed", "Not currently claimed"),
        ],
        "sections": [
            {"heading": "Content preparation and target labels", "paragraphs": ["Users can review and copy AI-assisted writing to an external platform. Target labels are organisational fields inside Creana; they do not establish an official integration."]},
            {"heading": "Current integration boundaries", "paragraphs": ["Creana does not currently claim external social-account analytics import or automatic publishing through external platform APIs. Creana analytics use activity generated or tracked inside Creana."]},
        ], "related": ("ai_features", "how_it_works", "faq"),
    },
    "how_it_works": {
        "route_name": "how_it_works", "title": "How Creana Works | Six-Step Content Workflow",
        "description": "Follow Creana's workflow from creating an account and drafting content to sharing inside Creana and reviewing in-platform analytics.",
        "eyebrow": "How it works", "heading": "What is the Creana workflow?",
        "lead": "The workflow moves from an initial idea to an informed next piece of content in six steps.",
        "sections": [
            {"heading": "1. Create an account", "paragraphs": ["Create a Creana profile and sign in."]},
            {"heading": "2. Create a post or campaign", "paragraphs": ["Start new content or organise related posts around a campaign objective."]},
            {"heading": "3. Use AI writing support", "paragraphs": ["Request writing assistance where useful, then review and edit the output."]},
            {"heading": "4. Publish, share, or manage content inside Creana", "paragraphs": ["Save a draft, choose visibility, publish, or schedule a future release inside Creana."]},
            {"heading": "5. Review Creana-collected analytics", "paragraphs": ["Review available views, engagement, campaign activity, and, where available, video watch retention recorded within Creana."]},
            {"heading": "6. Improve future content", "paragraphs": ["Use what you learned to inform the next post or campaign."]},
        ], "related": ("features", "ai_features", "supported_platforms"),
    },
    "faq": {
        "route_name": "faq", "title": "Creana FAQ | AI Content and Analytics Questions",
        "description": "Answers about Creana's AI captions, supported content workflows, in-platform analytics, video retention, membership, privacy, and beginner use.",
        "eyebrow": "FAQ", "heading": "Frequently asked questions about Creana", "lead": "Short answers to common questions, with links to the authoritative page.",
        "sections": [
            {"heading": "What is Creana?", "paragraphs": ["Creana is an AI-powered social media content workspace."], "link": ("introduction", "Read the introduction")},
            {"heading": "Who should use Creana?", "paragraphs": ["Creana is intended for creators, influencers, students, beginners, and small businesses."], "link": ("introduction", "See who Creana is for")},
            {"heading": "Is Creana an AI caption generator?", "paragraphs": ["Yes. Caption generation is one of several Creana AI tools."], "link": ("ai_features", "Explore AI features")},
            {"heading": "Can I use Creana captions on TikTok or Instagram?", "paragraphs": ["Yes. Review and copy the writing to the intended external platform."], "link": ("supported_platforms", "Review platform support")},
            {"heading": "Does Creana analyze my Instagram or TikTok account?", "paragraphs": ["Creana does not currently claim external social-account analytics import."], "link": ("supported_platforms", "See integration boundaries")},
            {"heading": "Where does Creana analytics data come from?", "paragraphs": ["It comes from relevant activity generated or tracked inside Creana."], "link": ("ai_features", "See which tools require Creana data")},
            {"heading": "Can I upload videos?", "paragraphs": ["Yes, subject to the formats, limits, and availability shown in the application."], "link": ("features", "Explore content features")},
            {"heading": "What is video retention analysis?", "paragraphs": ["It describes viewing and timed engagement recorded for a video inside Creana."], "link": ("features", "Learn about retention insights")},
            {"heading": "Is Creana free?", "paragraphs": ["Community access is available under current account rules; member-only functionality requires membership."], "link": ("pricing", "Compare access")},
            {"heading": "What does membership unlock?", "paragraphs": ["Membership unlocks functionality marked as members-only, including AI features."], "link": ("pricing", "Review membership")},
            {"heading": "Can beginners use Creana?", "paragraphs": ["Yes. Creana provides a guided content workflow."], "link": ("how_it_works", "See how it works")},
            {"heading": "Is my private content indexed by Google?", "paragraphs": ["Creana does not intentionally expose private, draft, or scheduled posts to anonymous visitors or the public sitemap."], "link": ("privacy", "Read about data visibility")},
        ], "related": ("introduction", "privacy", "pricing"), "faq_schema": True,
    },
    "about": {
        "route_name": "about", "title": "About Creana | Product Mission",
        "description": "Learn about Creana's mission to make content creation, campaign planning, community sharing, and in-platform performance learning easier.",
        "eyebrow": "About", "heading": "Why does Creana exist?", "lead": "Creana was created to bring content creation and learning closer together.",
        "sections": [
            {"heading": "Our mission", "paragraphs": ["Creana aims to make planning, creating, sharing, and learning from content feel more connected and approachable."]},
            {"heading": "Our product philosophy", "paragraphs": ["A content workspace should support creative judgement, provide useful context, and make its boundaries clear."]},
            {"heading": "AI should assist, not replace", "paragraphs": ["Creana treats AI as an assistant for drafting and interpreting available signals. People remain responsible for reviewing output and making publishing decisions."]},
            {"heading": "Truthful product information", "paragraphs": ["Creana is committed to describing current capabilities accurately and distinguishing existing functionality from future possibilities."]},
        ], "related": ("contact", "privacy", "terms"), "organization_schema": True,
    },
    "contact": {
        "route_name": "contact", "title": "Contact Creana | Support Information",
        "description": "Find current guidance for contacting Creana and learn what information to include in a support request.",
        "eyebrow": "Contact", "heading": "How can users get help?", "lead": "Creana does not currently publish a general support email or public contact form.",
        "sections": [
            {"heading": "Current contact path", "paragraphs": ["Use any official support or contact option presented inside your Creana account. This page will be updated when a verified public channel is available."]},
            {"heading": "What to include", "bullets": ["A concise description of the issue", "The page or feature involved", "What you expected and what happened", "Non-sensitive reproduction steps or screenshots"]},
            {"heading": "Protect sensitive information", "paragraphs": ["Do not send passwords, payment-card details, authentication tokens, or unnecessary personal information in a support request."]},
        ], "related": ("faq", "privacy", "terms"),
    },
    "privacy": {
        "route_name": "privacy", "title": "Creana Privacy Policy",
        "description": "Read Creana's plain-language privacy policy draft covering accounts, uploaded content, analytics, AI features, sessions, and public visibility.",
        "eyebrow": "Privacy policy", "heading": "What information does Creana process?", "lead": "This plain-language policy draft was last updated on 2 July 2026 and requires jurisdiction-specific legal review.",
        "sections": [
            {"heading": "Information Creana processes", "paragraphs": ["Creana may process account details, profile information, uploaded content and media, membership status, preferences, and account-related timestamps."]},
            {"heading": "Analytics and community activity", "paragraphs": ["Creana may record views, likes, comments, shares, follows, campaign relationships, watch sessions, retention, and timed engagement to operate in-platform features."]},
            {"heading": "Public and private visibility", "paragraphs": ["Public content may be visible to visitors and search engines. Private, draft, and scheduled content is not intended for anonymous access or inclusion in the public sitemap."]},
            {"heading": "AI feature data", "paragraphs": ["Content details and relevant Creana activity may be processed to provide requested AI output. Avoid submitting confidential or sensitive information unnecessarily; see the AI Policy for responsible use."]},
            {"heading": "Cookies and technical data", "paragraphs": ["Creana uses session mechanisms for sign-in, security, preferences, and service operation. Technical records may include request, browser, device, network, and error information."]},
            {"heading": "Why information is used", "bullets": ["Provide and secure accounts", "Store and display content according to visibility", "Operate community, scheduling, analytics, membership, and AI features", "Diagnose errors, prevent misuse, and improve the service"]},
            {"heading": "Requests and contact", "paragraphs": ["A verified privacy contact and complete information about retention, processors, user rights, and request procedures still need to be established before this draft is treated as a final legal policy."]},
        ], "related": ("ai_policy", "contact", "terms"),
    },
    "terms": {
        "route_name": "terms", "title": "Creana Terms of Service",
        "description": "Read Creana's plain-language service terms draft covering accounts, user content, prohibited behaviour, membership, availability, and disclaimers.",
        "eyebrow": "Terms of service", "heading": "What rules govern use of Creana?", "lead": "These plain-language draft terms were last updated on 2 July 2026 and require jurisdiction-specific legal review.",
        "sections": [
            {"heading": "Use of the service", "paragraphs": ["Users must provide accurate account information, protect their credentials, and use Creana lawfully and responsibly."]},
            {"heading": "User content", "paragraphs": ["Users are responsible for content they create, upload, publish, comment on, or share and for having the necessary rights and permissions."]},
            {"heading": "Community and AI obligations", "paragraphs": ["Users must follow the Community Guidelines and AI Policy. Creana may remove content or restrict accounts when conduct violates applicable rules or creates safety, security, or legal risks."]},
            {"heading": "Membership and payment", "paragraphs": ["Member-only features require active access. Users should review the current price and checkout terms before payment. Failed or ended payments may remove member access."]},
            {"heading": "Service availability and changes", "paragraphs": ["Creana may change, restrict, suspend, or discontinue functionality for maintenance, security, legal compliance, enforcement, or product development. Continuous availability is not guaranteed."]},
            {"heading": "Disclaimer", "paragraphs": ["AI output and analytics suggestions may be inaccurate or unsuitable. Users remain responsible for their publishing, business, legal, and safety decisions."]},
        ], "related": ("community", "ai_policy", "pricing"),
    },
    "ai_policy": {
        "route_name": "ai_policy", "title": "Creana AI Usage Policy",
        "description": "Learn how Creana's AI writing and in-platform analytics features work, their limitations, and the rules for responsible use.",
        "eyebrow": "AI usage policy", "heading": "How should Creana AI be used responsibly?", "lead": "AI output is assistance for human review, not a guarantee of accuracy, suitability, or performance. Last updated: 2 July 2026.",
        "sections": [
            {"heading": "Review every output", "paragraphs": ["AI output may contain errors, omissions, bias, unsuitable wording, or unsupported conclusions. Verify facts, rights, tone, and platform requirements before relying on it."]},
            {"heading": "Protect sensitive information", "paragraphs": ["Do not submit passwords, authentication tokens, payment-card details, private identifiers, confidential business information, or unnecessary personal data."]},
            {"heading": "Use AI responsibly", "paragraphs": ["Do not use Creana AI to create illegal, abusive, hateful, sexually exploitative, fraudulent, infringing, impersonating, or dangerously misleading content."]},
            {"heading": "Understand the analysis boundary", "paragraphs": ["AI analysis depends on relevant posts, campaigns, engagement, views, watch sessions, and retention activity generated or tracked inside Creana."]},
            {"heading": "Models and availability may change", "paragraphs": ["AI providers, models, limits, and functionality may change. Creana may restrict output or access for safety, reliability, cost, or policy reasons."]},
        ], "related": ("ai_features", "privacy", "terms"),
    },
}
