# Generated by Codex on 2026-04-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_live_counts(apps, schema_editor):
    social_media_post = apps.get_model("socialmanager", "SocialMediaPost")
    for post in social_media_post.objects.all():
        latest_metric = post.metrics.order_by("-captured_at").first()
        if latest_metric:
            post.likes_count = latest_metric.likes
            post.shares_count = latest_metric.shares
            post.save(update_fields=["likes_count", "shares_count"])


class Migration(migrations.Migration):

    dependencies = [
        ("socialmanager", "0002_postcomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediapost",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="shares_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PostEngagement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("like", "Like"), ("share", "Share")], max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="engagements", to="socialmanager.socialmediapost")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="post_engagements", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("post", "user", "kind")},
            },
        ),
        migrations.RunPython(seed_live_counts, migrations.RunPython.noop),
    ]
