# Generated by Codex on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("socialmanager", "0004_userfollow"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediapost",
            name="article_caption",
            field=models.TextField(blank=True),
        ),
    ]
