# Generated by Codex on 2026-04-30

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_images(apps, schema_editor):
    SocialMediaPost = apps.get_model("socialmanager", "SocialMediaPost")
    PostImage = apps.get_model("socialmanager", "PostImage")
    for post in SocialMediaPost.objects.exclude(image="").exclude(image__isnull=True):
        if post.content_format == "image":
            PostImage.objects.get_or_create(
                post=post,
                image=post.image,
                defaults={"order": 0},
            )


class Migration(migrations.Migration):
    dependencies = [
        ("socialmanager", "0005_socialmediapost_article_caption"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="social_posts/")),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="socialmanager.socialmediapost")),
            ],
            options={
                "ordering": ["order", "created_at", "pk"],
            },
        ),
        migrations.RunPython(copy_legacy_images, migrations.RunPython.noop),
    ]
