# Generated by Codex on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmanager", "0007_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediapost",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="social_videos/"),
        ),
    ]
