# Generated by Codex on 2026-05-04

from django.db import migrations, models


def migrate_planning_to_draft(apps, schema_editor):
    SocialMediaCampaign = apps.get_model("socialmanager", "SocialMediaCampaign")
    SocialMediaCampaign.objects.filter(status="planning").update(status="draft")


def migrate_draft_to_planning(apps, schema_editor):
    SocialMediaCampaign = apps.get_model("socialmanager", "SocialMediaCampaign")
    SocialMediaCampaign.objects.filter(status="draft").update(status="planning")


class Migration(migrations.Migration):

    dependencies = [
        ("socialmanager", "0008_socialmediapost_video_file"),
    ]

    operations = [
        migrations.RunPython(migrate_planning_to_draft, migrate_draft_to_planning),
        migrations.AlterField(
            model_name="aisuggestionhistory",
            name="platform",
            field=models.CharField(
                choices=[
                    ("tiktok", "TikTok"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("facebook", "Facebook"),
                    ("x", "X / Twitter"),
                    ("linkedin", "LinkedIn"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="socialmediacampaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="socialmediapost",
            name="platform",
            field=models.CharField(
                choices=[
                    ("tiktok", "TikTok"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("facebook", "Facebook"),
                    ("x", "X / Twitter"),
                    ("linkedin", "LinkedIn"),
                ],
                max_length=20,
            ),
        ),
    ]
