# Generated by Django 6.0.4 on 2026-05-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmanager', '0014_videoengagementevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='videoengagementevent',
            new_name='socialmanag_post_id_6cd86f_idx',
            old_name='socialmanag_post_id_96b7f9_idx',
        ),
        migrations.RenameIndex(
            model_name='videowatchsession',
            new_name='socialmanag_post_id_194677_idx',
            old_name='socialmanag_post_id_1d0239_idx',
        ),
    ]
