# Generated by Django 6.0.5 on 2026-06-04 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_settings_for_existing_users(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    UserSettings = apps.get_model("socialmanager", "UserSettings")
    for user in User.objects.all():
        UserSettings.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('socialmanager', '0018_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('zh-hant', 'Traditional Chinese')], default='en', max_length=20)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=20)),
                ('notify_like', models.BooleanField(default=True)),
                ('notify_comment', models.BooleanField(default=True)),
                ('notify_share', models.BooleanField(default=True)),
                ('notify_follow', models.BooleanField(default=True)),
                ('ai_tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('marketing', 'Marketing'), ('casual', 'Casual')], default='professional', max_length=20)),
                ('ai_language', models.CharField(choices=[('english', 'English'), ('traditional_chinese', 'Traditional Chinese'), ('auto', 'Auto Detect')], default='auto', max_length=30)),
                ('ai_hashtag_count', models.PositiveSmallIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.RunPython(create_settings_for_existing_users, migrations.RunPython.noop),
    ]
