# Generated by Django 6.0.5 on 2026-06-05 04:15

from django.db import migrations, models


def clamp_hashtag_count(apps, schema_editor):
    UserSettings = apps.get_model("socialmanager", "UserSettings")
    UserSettings.objects.filter(ai_hashtag_count__gt=5).update(ai_hashtag_count=5)
    UserSettings.objects.filter(ai_hashtag_count__lt=1).update(ai_hashtag_count=5)


class Migration(migrations.Migration):

    dependencies = [
        ('socialmanager', '0019_usersettings'),
    ]

    operations = [
        migrations.RunPython(clamp_hashtag_count, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='usersettings',
            name='ai_hashtag_count',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
