# Generated by Django 6.0.5 on 2026-06-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmanager', '0020_alter_usersettings_ai_hashtag_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediacampaign',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
