# Generated by Django 6.0.5 on 2026-06-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmanager', '0022_postcomment_liked_by_postcomment_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
