# Generated by Django 6.0.5 on 2026-06-08 06:54

import django.db.models.deletion
from django.db import migrations, models


def backfill_reply_notifications(apps, schema_editor):
    Notification = apps.get_model("socialmanager", "Notification")
    Notification.objects.filter(
        kind="comment",
        comment__isnull=False,
        comment__parent__isnull=False,
    ).update(is_reply=True)


def clear_reply_notifications(apps, schema_editor):
    Notification = apps.get_model("socialmanager", "Notification")
    Notification.objects.update(is_reply=False)


class Migration(migrations.Migration):

    dependencies = [
        ('socialmanager', '0023_postcomment_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='socialmanager.postcomment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='socialmanager.socialmediapost'),
        ),
        migrations.RunPython(backfill_reply_notifications, clear_reply_notifications),
    ]
