# Generated by Django 6.0.5 on 2026-06-10 01:20

from django.db import migrations, models


def promote_reply_notifications(apps, schema_editor):
    Notification = apps.get_model("socialmanager", "Notification")
    Notification.objects.filter(kind="comment", is_reply=True).update(kind="comment_reply")


def demote_reply_notifications(apps, schema_editor):
    Notification = apps.get_model("socialmanager", "Notification")
    Notification.objects.filter(kind="comment_reply").update(kind="comment", is_reply=True)


class Migration(migrations.Migration):

    dependencies = [
        ('socialmanager', '0024_notification_is_reply_alter_notification_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('like', 'Like'), ('share', 'Share'), ('comment', 'Comment'), ('comment_reply', 'Comment reply'), ('comment_like', 'Comment like'), ('follow', 'Follow')], max_length=20),
        ),
        migrations.RunPython(promote_reply_notifications, demote_reply_notifications),
    ]
