# Generated by Django 6.0.5 on 2026-06-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmanager', '0025_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_video_thumbnails/'),
        ),
    ]
