# Generated by Django 6.0.5 on 2026-06-11 07:13

from django.db import migrations, models


def copy_legacy_notification_preferences(apps, schema_editor):
    UserSettings = apps.get_model("socialmanager", "UserSettings")
    for settings_obj in UserSettings.objects.all().iterator():
        settings_obj.notify_post_like = settings_obj.notify_like
        settings_obj.notify_comment_like = settings_obj.notify_like
        settings_obj.notify_post_comment = settings_obj.notify_comment
        settings_obj.notify_comment_reply = settings_obj.notify_comment
        settings_obj.notify_post_share = settings_obj.notify_share
        settings_obj.save(
            update_fields=[
                "notify_post_like",
                "notify_comment_like",
                "notify_post_comment",
                "notify_comment_reply",
                "notify_post_share",
            ]
        )


def copy_split_notification_preferences_to_legacy(apps, schema_editor):
    UserSettings = apps.get_model("socialmanager", "UserSettings")
    for settings_obj in UserSettings.objects.all().iterator():
        settings_obj.notify_like = settings_obj.notify_post_like
        settings_obj.notify_comment = settings_obj.notify_post_comment
        settings_obj.notify_share = settings_obj.notify_post_share
        settings_obj.save(update_fields=["notify_like", "notify_comment", "notify_share"])


class Migration(migrations.Migration):

    dependencies = [
        ('socialmanager', '0026_socialmediapost_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='notify_comment_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notify_comment_reply',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notify_post_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notify_post_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notify_post_share',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(
            copy_legacy_notification_preferences,
            copy_split_notification_preferences_to_legacy,
        ),
    ]
