# Generated by Codex on 2026-06-17

from django.conf import settings
from django.db import migrations, models


def activate_creana_official_member(apps, schema_editor):
    UserModel = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    SaaSSubscription = apps.get_model("socialmanager", "SaaSSubscription")
    SubscriptionMembership = apps.get_model("socialmanager", "SubscriptionMembership")

    user = UserModel.objects.filter(username="Creana_official").first()
    if not user:
        return

    subscription = (
        SaaSSubscription.objects.filter(owner=user, is_archived=False)
        .order_by("created_at")
        .first()
    )
    if not subscription:
        subscription = SaaSSubscription.objects.create(
            name="Creana Official Workspace",
            owner=user,
            plan="pro",
        )

    membership, _ = SubscriptionMembership.objects.get_or_create(
        subscription=subscription,
        user=user,
        defaults={
            "role": "admin",
            "is_active_member": True,
        },
    )
    if not membership.is_active_member:
        membership.is_active_member = True
        membership.save(update_fields=["is_active_member"])


def deactivate_creana_official_member(apps, schema_editor):
    UserModel = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    SubscriptionMembership = apps.get_model("socialmanager", "SubscriptionMembership")

    user = UserModel.objects.filter(username="Creana_official").first()
    if not user:
        return
    SubscriptionMembership.objects.filter(user=user).update(is_active_member=False)


class Migration(migrations.Migration):

    dependencies = [
        ("socialmanager", "0027_usersettings_notify_comment_like_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionmembership",
            name="is_active_member",
            field=models.BooleanField(
                "Active member",
                default=True,
                help_text="Allows this user to access member-only AI tools.",
            ),
        ),
        migrations.RunPython(
            activate_creana_official_member,
            deactivate_creana_official_member,
        ),
    ]
