# Generated by Django 6.0.5 on 2026-06-24 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmanager', '0030_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hidden_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by_users', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'hidden_user'), name='unique_hidden_user_owner'), models.CheckConstraint(condition=models.Q(('owner', models.F('hidden_user')), _negated=True), name='prevent_self_hidden_user')],
            },
        ),
    ]
