# Generated by Django 6.0.5 on 2026-06-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmanager', '0031_hiddenuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='social_posts/thumbnails/'),
        ),
    ]
