# Generated by Django 6.0.5 on 2026-06-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmanager', '0032_postimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='profile_avatars/thumbnails/'),
        ),
    ]
